### ISSUE TITLE
Js error

### ISSUE THREAD

**Issue by iw3hxn** [iw3hxn/LibrERP#8]
When enter on a product:

find this 2 error:

Uncaught TypeError: Cannot read property 'containerElement' of undefined
http://10.126.1.150:8069/web/webclient/js:33293

TypeError: self.tags is undefined
http://10.126.1.150:8069/web/webclient/js:33293

**Comment by dhp-denero** [comment]
Ok, I will look and back to you with fix

**Comment by iw3hxn** [comment]
render_tag: function(data) {
        var self = this;
        if (! self.readonly) {
            self.tags.containerElement().children().remove();
            self.$input.css("padding-left", "3px");
            self.tags.addTags(self.map_tag(data));
        } else {
            self.$element.html(QWeb.render(self.tag_template, {elements: data}));
        }
    },

**Comment by dhp-denero** [comment]
OK

Thanks for sharing exact code

**Comment by dhp-denero** [comment]
Hello Carlo,

I have worked on Errors, We are not getting an error at line self.tags.
we are getting bellow error only. 
Uncaught TypeError: Cannot read property 'containerElement' of undefined

we are going to fix it.

Thanks

**Comment by iw3hxn** [comment]
Merge pull request #10 from dhp-denero/master FIX
